//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using AssemblyCSharp;

[System.Serializable]
public enum PotionType {
	HP,
	MaxHP,
	EXP,
	SP,
    CDR,
    MOV,
    DoubleAttack

}
[System.Serializable]
public abstract class Item {
	
	private String name;
    [HideInInspector]
    public Sprite sprite;
    private int usage = 1;
    public bool droppedOnDeath = false;
	private string description;
	public GameObject gameobject;
	public Item(String name, String description, int useage, Sprite sprite, GameObject go){
		this.name = name;
		this.description = description;
        this.usage = useage;
        this.sprite = sprite;
		this.gameobject = go;
	}
    public int Usage {
		get { return usage;}
		set { usage = value;
            
        }
	}
	public String Description {
		get { return description;}
		set { description = value;}
	}
	public String Name {
		get { return name;}
		set { name = value;}
	}
	
	public abstract void use(Character character);


}


