//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using AssemblyCSharp;

[System.Serializable]
public enum PotionType {
	HP,
	MaxHP,
	EXP,
	SP,
    CDR,
    MOV,
    DoubleAttack

}
[System.Serializable]
public abstract class Item {
	
	private String name;
    [HideInInspector]
    public Sprite sprite;
    [HideInInspector]
    public Sprite sprite_hovered;
    [HideInInspector]
    public Sprite sprite_pressed;
    private int usage = 1;
    public bool droppedOnDeath = false;
	private string description;
	public GameObject gameobject;
	public GameObject gameobject3d;
	public Item(String name, String description, int useage, Sprite sprite, Sprite hovered, Sprite pressed, GameObject go,  GameObject go3d){
		this.name = name;
		this.description = description;
        this.usage = useage;
        this.sprite = sprite;
        this.sprite_hovered = hovered;
        this.sprite_pressed = pressed;
		this.gameobject = go;
		this.gameobject3d = go3d;
	}
	public Item(String name, String description, int useage, Sprite sprite, Sprite hovered, Sprite pressed, GameObject go, GameObject go3d, bool dropOnDeath)
    {
        this.name = name;
        this.usage = useage;
		this.description = description;
        this.sprite = sprite;
        this.sprite_hovered = hovered;
        this.sprite_pressed = pressed;
        this.droppedOnDeath = dropOnDeath;
		this.gameobject = go;
		this.gameobject3d = go3d;
    }
    public int Usage {
		get { return usage;}
		set { usage = value;
            
        }
	}
	public String Description {
		get { return description;}
		set { description = value;}
	}
	public String Name {
		get { return name;}
		set { name = value;}
	}
	
	public abstract void use(Character character);

    public void drop(Character character)
    {
		GameObject.Find (MainScript.MAIN_GAME_OBJ).GetComponent<MainScript> ().NewItemDrop (new ItemDrop (this, character.x, character.z));
    }

}


