//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Assets.Scripts.Characters.Skills;
using System;
using UnityEngine;
using Assets.Scripts.GameStates;

[System.Serializable]
	public class Potion : Item {

    public int Effect { get; set; }

    public Potion(String name, String description, int useage,  int effect,Sprite sprite):base(name, description, useage, sprite) {
        Effect = effect;
    }

	public override void use(Human character) {
        NumberOfUses--;
		if (NumberOfUses <= 0)
			character.Inventory.DropItem(this);	
	}
		

		
}


