//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Assets.Scripts.Characters.Skills;
using System;
using UnityEngine;
using Assets.Scripts.GameStates;

[System.Serializable]
	public class Potion : Item {
		
		private PotionType attribute;
		private int effect;
		
	public Potion(String name, String description, int useage, PotionType attribute, int effect,Sprite sprite, Sprite hovered, Sprite pressed, GameObject go, GameObject go3d, bool droppedOnDeath):base(name, description, useage, sprite, hovered, pressed, go,go3d, droppedOnDeath) {
			this.effect = effect;
			this.attribute = attribute;
          
    }

		public override void use(Character character) {
		
			switch(attribute){
		case PotionType.HP:
			character.Heal (effect);
			MainScript.healthPotionUsedEvent ();
			break;
		case PotionType.EXP:
			character.addExp(effect);
			MainScript.healthPotionUsedEvent ();
			break;
			    case PotionType.MaxHP: character.stats.maxHP+= effect;break;
                case PotionType.CDR:
                foreach(Skill s in character.charclass.skills)
                {
                    s.CurrentCooldown = 0;
                }
                break;
                //case Attribute.DoubleAttack:
                //    character.doubleAttack = true; break;
                case PotionType.MOV:
                    character.charclass.movRange += 1; break;
			}
		Usage--;
		if (Usage <= 0)
			character.items.Remove(this);
           // GameObject.Find("ItemMessage").GetComponent<ItemMessage>().Show(this);
        GameObject.Find(MainScript.MAIN_GAME_OBJ).GetComponent<MainScript>().ActiveCharWait();

		GameObject.Find(MainScript.MAIN_GAME_OBJ).GetComponent<MainScript>().SwitchState(new GameplayState());
         
       
			
		}
		
		public PotionType Attribute {
			get{ return attribute;}
			set{ attribute = value;}
		}
		public int Effect {
			get{ return effect;}
			set{ effect = value;}
		}
		
	}


