//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Assets.Scripts.Characters.Skills;
using System;
using UnityEngine;
using Assets.Scripts.GameStates;

[System.Serializable]
	public class Potion : Item {
		
		private PotionType attribute;
		private int effect;
		
	public Potion(String name, String description, int useage, PotionType attribute, int effect,Sprite sprite, Sprite hovered, Sprite pressed, GameObject go, GameObject go3d, bool droppedOnDeath):base(name, description, useage, sprite, hovered, pressed, go,go3d, droppedOnDeath) {
			this.effect = effect;
			this.attribute = attribute;
          
    }

	public override void use(Character character) {
		
		switch(attribute){
		case PotionType.HP:
			//character.Heal (effect);
			MainScript.healthPotionUsedEvent ();
			break;
		
		}
		Usage--;
		if (Usage <= 0)
			character.items.Remove(this);
         
       
			
	}
		
	public PotionType Attribute {
		get{ return attribute;}
		set{ attribute = value;}
	}
	public int Effect {
		get{ return effect;}
		set{ effect = value;}
	}
		
}


