//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Assets.Scripts.Characters.Skills;
using System;
using UnityEngine;
using Assets.Scripts.GameStates;
using Assets.Scripts.Characters;

[System.Serializable]
public abstract class ItemMixin : ScriptableObject {
    public new string name;
	public abstract void Use(LivingObject character);
		
}


